"""Side-by-side SVG diff viewer (B+2 item 1.5).

Render before/after SVGs into a single HTML file for visual A/B inspection on
any rendering-affecting change. Catches issues that snap metrics miss
(24-lets, 48-lets, missing key signatures, fractional BPM displays).

Usage
-----
python scripts/compare_svgs.py before.svg after.svg --out outputs/compare.html
python scripts/compare_svgs.py --pairs before1.svg after1.svg before2.svg after2.svg
"""
from __future__ import annotations
import argparse
import html
from pathlib import Path


_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>HumScribe SVG comparison</title>
<style>
body {{ font-family: -apple-system, sans-serif; background: #f6f7f9; margin: 24px; color: #222; }}
h1 {{ font-size: 18px; margin-top: 0; }}
.pair {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; padding: 12px;
        background: #fff; border: 1px solid #ddd; border-radius: 6px; margin-bottom: 18px; }}
.col h2 {{ font-size: 14px; color: #555; margin: 0 0 8px 0; padding-bottom: 4px; border-bottom: 1px solid #eee; }}
.col svg, .col img {{ max-width: 100%; background: #fff; border: 1px solid #f0f0f0; }}
.note {{ font-size: 12px; color: #777; }}
</style>
</head>
<body>
<h1>HumScribe rendering A/B</h1>
<p class="note">Left: before. Right: after. Generated by scripts/compare_svgs.py.</p>
{pairs}
</body>
</html>
"""


def _embed(svg_path: Path) -> str:
    if not svg_path.exists():
        return f'<p style="color:#c33">missing: {html.escape(str(svg_path))}</p>'
    text = svg_path.read_text()
    if "<svg" in text:
        return text
    return f"<pre>{html.escape(text[:1000])}</pre>"


def render_pairs(pairs: list[tuple[Path, Path]], out: Path, label_pairs: list[tuple[str, str]] | None = None) -> Path:
    blocks = []
    for i, (before, after) in enumerate(pairs):
        if label_pairs and i < len(label_pairs):
            lb, la = label_pairs[i]
        else:
            lb, la = before.name, after.name
        blocks.append(
            f'<div class="pair">'
            f'<div class="col"><h2>{html.escape(lb)}</h2>{_embed(before)}</div>'
            f'<div class="col"><h2>{html.escape(la)}</h2>{_embed(after)}</div>'
            f'</div>'
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_TEMPLATE.format(pairs="\n".join(blocks)))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Render side-by-side SVG comparison.")
    ap.add_argument("paths", nargs="*", help="positional pairs: before1 after1 [before2 after2 ...]")
    ap.add_argument("--out", default="outputs/svg_compare.html")
    args = ap.parse_args()
    if len(args.paths) < 2 or len(args.paths) % 2 != 0:
        ap.error("need an even number of paths (pairs of before/after)")
    pairs = []
    for i in range(0, len(args.paths), 2):
        pairs.append((Path(args.paths[i]), Path(args.paths[i + 1])))
    out = render_pairs(pairs, Path(args.out))
    print(f"wrote {out}  ({len(pairs)} pair(s))")


if __name__ == "__main__":
    main()
